version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    expose:
      - "80"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    expose:
      - "5008"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workout_app
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_refresh_jwt_secret
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workout_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
